### ISSUE TITLE
Full Update class 'KeyError'

### ISSUE THREAD

**Issue by Crimson1110** [netdevopsbr/netbox-proxbox#41]
On a fresh install of Netbox, I am having this error as soon as I try to do a full update:

Server Error

There was a problem with your request. Please contact an administrator.

The complete exception is provided below:

<class 'KeyError'>

'errors'

Python version: 3.8.10
NetBox version: 3.0.0

If further assistance is required, please post to the [NetBox mailing list](https://groups.google.com/g/netbox-discuss).
[Home Page](https://192.168.1.139/)

**Comment by emersonfelipesp** [comment]
Could you please try running it on django development mode using **python3 manage.py runserver 0.0.0.0:8000 --insecure** and provide out terminal output error here?
Also, try using the last version released to se if maybe the problem is already solved!

**Comment by Crimson1110** [comment]
Perhaps I need to test it on fresh install of Netbox, but for now the error is still there with the last version.

and the manage.py gave this error:
ModuleNotFoundError: No module named 'django'

I installed the requirements.txt
then it started to give this error:
manage.py runserver: error: unrecognized arguments: --insecure

on venv it starts normally but when I try to do the Proxmox full update, it still gives the keyerror.

Am I doing something wrong?

**Comment by emersonfelipesp** [comment]
### Try following steps:
1. Enter Netbox Virtual Environment

```
source /opt/netbox/venv/bin/activate
```

2. Start Django server on **port 8000** for testing purposes, it shows real-time logging on Linux terminal.
```
cd /opt/netbox/netbox
python3 manage.py runserver 0.0.0.0:8000 --insecure
```

3. Open your Netbox on Web Browser using the following URL format: `http://<your-ip-address>:8000`
> **WARNING:** You **MUST** use **http://** instead of **https://**, because the **--insecure** argument is to do exactly that: to not use HTTPS. If not, it will probably occur HTTP error and the page will not even open if not using HTTP.

If you get the same errors again, copy the full logging output you got on Linux terminal so I can help you to solve it!

**Comment by emersonfelipesp** [comment]
> i am running into the same issue (on a fresh netbox install, with the plugin installed according to the instructions.

Hi @JacobdeBrouwer, what Netbox version are you using and are you running the last Proxbox version released (v0.0.4)?

**Comment by JacobdeBrouwer** [comment]
@emersonfelipesp i am running netbox 3.2.2 and using proxbox cloned from the github's master repository. (i had other issues in the PIP release). 

also, i am running both on a debian 11 VM with python 3.9.

**Comment by emersonfelipesp** [comment]
Are you using [develop branch](https://github.com/netdevopsbr/netbox-proxbox/tree/develop) (which is the default one)?
Does Netbox GUI (webpage) shows any errors? Or it just does not open?

**Comment by JacobdeBrouwer** [comment]
i am running the default branch (which indeed seems to be development).

see the attached screenshot for details on what the GUI shows:

![image](https://user-images.githubusercontent.com/1040803/167937457-7c931600-0a1d-4517-9e20-c29f8ceb2520.png)

**Comment by emersonfelipesp** [comment]
> i am running the default branch (which indeed seems to be development).
> 
> see the attached screenshot for details on what the GUI shows:
> 
> ![image](https://user-images.githubusercontent.com/1040803/167937457-7c931600-0a1d-4517-9e20-c29f8ceb2520.png)

What Proxmox version are you running? Does Proxbox created any object on Netbox?
Also, let me know if you have Virtual Machines or Containers with the same name, because I think there is a bug related to it.

**Comment by ettorsson** [comment]
I am having the same problem.
![image](https://user-images.githubusercontent.com/12773062/168386427-be11a882-ee1d-4a6e-8c69-4e7522919ef1.png)

I am using Proxmox 7.2-3.
Netbox version 0.0.4

I have no vms with same name, I had one but still the same problem after changing the name.

**Comment by emersonfelipesp** [comment]
> I am having the same problem. ![image](https://user-images.githubusercontent.com/12773062/168386427-be11a882-ee1d-4a6e-8c69-4e7522919ef1.png)
> 
> I am using Proxmox 7.2-3. Netbox version 0.0.4
> 
> I have no vms with same name, I had one but still the same problem after changing the name.

Maybe the problem is related to **Proxmox >7.x.x** as all my development environment runs Proxmox with version 6.x.x.
I will upgrade one of my servers to latest Proxmox version and comeback here to show my results.

**Comment by emersonfelipesp** [comment]
Hi, could you please try testing it again, if possible? There was several new updates to code since then. Thank you already!

**Comment by emersonfelipesp** [comment]
As there was no interactions since then, closing this issue.
